### PR TITLE
[UrlButtons] Create `tr-TR.po`.

### PR DESCRIPTION
**Pull request by xBlackAttack**
Turkish language

### CODE REVIEW

**Comment by xBlackAttack** [comment]
I just saw Crowdin. If you can add Turkish, I can do it from there.

**Comment by AAA3A-AAA3A** [comment]
I add it right away to crowdin.

**Review by AAA3A-AAA3A — CHANGES_REQUESTED** [review]
As you said, the translation should be done on Crowdin, to avoid invalid files, have a better interface and allow easy editing of translations in the future, without losing your changes.

**Comment by AAA3A-AAA3A** [comment]
I added this language to the Crowdin project of my repo.
Thank you for the request to add this language and thank you in advance for the translation!

**Pull request closed without merging**
